### ISSUE TITLE
Shiny: find out what the resources are for learning the capabilities

### ISSUE THREAD

**Issue by eramire2** [bccpp/tool#15]

**Comment by mhalsted** [comment]
hi, I can work on putting together a ppt with general R information as well as links to helpful videos.

**Comment by eramire2** [comment]
sounds like a good idea... glad you are interacting through the github collaboration.

**Comment by mhalsted** [comment]
[Coding with R.pptx](https://github.com/bccpp/tool/files/89602/Coding.with.R.pptx)
